import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Button, Input } from "styled-landingpage";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form>
        <Input type="email" name="user" label="Usuário" />
        <Input type="password" name="password" label="Senha" />
        <Button>Enviar</Button>
      </form>
    </div>
  );
};

export default Home;
